import Link from "next/link";
import { Building2, BookOpen, FileCheck2, FileText, Calculator, MessageCircle, CircleCheck, ChartNoAxesCombined } from "lucide-react";
import { PageFrame, ConsultationCTA, Process } from "@/components/site-sections";
import { MotionDesk, FinancialStory } from "@/components/financial-motion";
import { TaxCalculator } from "@/components/tax-calculator";
import { ServiceFAQ } from "@/components/service-faq";
import { services } from "@/lib/services";
import { posts } from "@/lib/posts";
import { whatsapp } from "@/lib/business";
const icons={registration:Building2,accounting:BookOpen,tax:FileText,audit:FileCheck2,closure:CircleCheck,reporting:ChartNoAxesCombined};
export default function Home(){return <PageFrame>
 <section className="new-hero"><div className="container new-hero-grid"><div className="new-hero-copy"><span className="eyebrow">Financial & Tax Consultants</span><h1>You run<br/>the business.<br/><span>We handle<br className="hero-line"/> the details.</span></h1><p>Registration, accounts, tax and business closure. Clear guidance and practical support, so you know what to do next.</p><div className="hero-actions"><Link className="button primary" href="/register-business">I want to register a business</Link><a className="text-link" href={whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>WhatsApp us</a></div><p className="hero-reassurance">New or established, get support that fits your business.</p><Link className="hero-calculator-mobile" href="#tax-calculator"><Calculator size={17}/>Try the free tax calculator</Link></div><MotionDesk/></div><div className="container hero-quick-links"><Link href="/register-business">Register a business</Link><Link href="/monthly-plan">Manage my accounts</Link><Link href="/services#tax">Get help with tax & filings</Link><Link href="/services#closure">Close a business</Link><Link href="#tax-calculator"><Calculator size={18}/>Use the free tax calculator</Link></div></section>
 <section className="section services-overview" id="services"><div className="container"><div className="section-heading"><div><span className="eyebrow">What we do</span><h2>Support for every<br/><span>stage of your business.</span></h2></div><p>One service when you need it.<br/>Ongoing support when you want it.</p></div><div className="service-card-grid">{services.map(s=>{const Icon=icons[s.id];return <Link className="service-card" key={s.id} href={s.id==="registration"?"/register-business":`/services#${s.id}`}><div className="service-card-top"><Icon size={27}/><span>{s.number}</span></div><h3>{s.title}</h3><p>{s.summary}</p><span className="service-card-foot">{s.id==="accounting"?"From NPR 6,000 / month · VAT included":s.id==="audit"?"Company work from NPR 5,000 + VAT":s.id==="reporting"?"Reports explained in plain language":s.id==="tax"?"Tax clearance & annual filings":"A quote for your requirements"}</span></Link>;})}</div><Link className="text-link section-link" href="/services">View services, scope and fees</Link></div></section>
 <FinancialStory/>
 <section className="section homepage-calculator" id="tax-calculator"><div className="container"><div className="section-heading"><div><span className="eyebrow">Free business tax calculator · FY 2083/84</span><h2>A first look<br/><span>at your tax.</span></h2></div><p>Enter your annual figures here. See an estimate and how it was calculated, without leaving this page.</p></div><TaxCalculator/><p className="scope-note">Sole proprietor? Normal business-income slabs can give a 0% rate on the first NPR 10 lakh of taxable income. Eligible fixed or turnover-based rules may apply instead. <Link href="/register-business#tax">Compare structures and tax</Link>.</p></div></section>
 <section className="section monthly-feature" id="plans"><div className="container"><div className="section-heading"><div><span className="eyebrow">For the everyday work</span><h2>A routine for your accounts.<br/><span>More time for your business.</span></h2></div><p>Monthly bookkeeping, applicable tax support, reports and a conversation about what the numbers mean.</p></div><div className="monthly-prices"><Link href="/monthly-plan" className="monthly-price-card"><span>Business Essentials</span><strong>NPR 6,000<small> / month</small></strong><p>Accounts, filings and monthly consultation.</p><span className="read-label">Explore Essentials</span></Link><Link href="/monthly-plan" className="monthly-price-card"><span>Business Growth</span><strong>NPR 15,000<small> / month</small></strong><p>Deeper analysis of sales, costs, cash and next actions.</p><span className="read-label">Explore Growth</span></Link><div className="monthly-custom"><h3>Need a different scope?</h3><p>Let’s discuss your business and agree a custom arrangement.</p><Link className="text-link" href="/free-consultation?plan=custom">Discuss your requirements</Link></div></div><p className="scope-note">Both monthly fees include VAT. Government charges, tax payments and separately agreed project work are additional.</p></div></section>
 <section className="section" id="about"><div className="container"><div className="section-heading"><div><span className="eyebrow">Working together</span><h2>A clear next step.<br/>From the first conversation.</h2></div></div><Process/></div></section>
 <section className="section notebook-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">The business notebook</span><h2>Useful answers.<br/><span>Without the jargon.</span></h2></div><Link className="text-link" href="/blog">Read all articles</Link></div><div className="article-card-grid">{[posts.find(p=>p.slug==="register-a-business-nepal")!,posts.find(p=>p.slug==="monthly-accounting-checklist")!,posts.find(p=>p.slug==="closing-a-business-nepal")!].map((p,i)=><Link className="article-card" key={p.slug} href={`/blog/${p.slug}`}><div className={`article-cover cover-${i}`} aria-hidden="true"><span>HK / Notebook</span><strong>{["Start with clarity.","A little order. Every month.","A clear closing chapter."][i]}</strong><span>0{i+1}</span></div><span className="eyebrow">{p.category} · {p.readTime}</span><h3>{p.title}</h3><p>{p.description}</p><span className="read-label">Read the guide</span></Link>)}</div></div></section>
 <section className="section faq-section"><div className="container split-content"><div><span className="eyebrow">Questions we can help with</span><h2>Start with<br/><span>what’s on your mind.</span></h2><p className="faq-intro">Choose a question, read the answer and continue the conversation on WhatsApp.</p></div><ServiceFAQ/></div></section><ConsultationCTA/>
 </PageFrame>;}
