"use client";
import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Building2, BookOpen, FileCheck2, CircleCheck, Check } from "lucide-react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
const stages = [
 {id:"starting",label:"Starting",icon:Building2,title:"Make your business official.",text:"Understand the registration process, prepare the documents and start with the right setup.",items:["Choose a suitable business structure","Prepare registration documents","Understand your PAN and tax setup"],service:"registration",link:"Explore registration"},
 {id:"running",label:"Running",icon:BookOpen,title:"Bring order to the everyday.",text:"Keep accounts, payroll and tax work in a routine. Understand what your business earns and spends.",items:["Maintain accounts and reconcile the bank","Keep applicable tax filings on track","Review profit, costs and cash"],service:"accounting",link:"Explore monthly support"},
 {id:"reviewing",label:"Reviewing",icon:FileCheck2,title:"Get ready for the next review.",text:"Prepare financial reports, support your auditor and take care of annual filings and tax clearance.",items:["Prepare financial statements and schedules","Coordinate with your appointed auditor","Complete annual and tax-related work"],service:"audit",link:"Explore annual support"},
 {id:"closing",label:"Closing",icon:CircleCheck,title:"Close with a clear plan.",text:"Work through the accounts, outstanding obligations and formalities needed to close your business.",items:["Review remaining accounts and obligations","Prepare closure documentation","Coordinate registration and tax formalities"],service:"closure",link:"Explore business closure"},
];
export function BusinessJourney(){return <div className="journey-shell"><div className="journey-heading"><span className="eyebrow">A little guidance</span><h2>Where are you today?</h2><p>Choose a stage to see how we can help.</p></div><Tabs defaultValue="starting" className="journey-tabs"><TabsList className="journey-tab-list" aria-label="Your business stage">{stages.map(s=><TabsTrigger value={s.id} key={s.id}>{s.label}</TabsTrigger>)}</TabsList>{stages.map(s=><TabsContent value={s.id} key={s.id} className="journey-panel"><div className="journey-service"><s.icon size={26}/><span>{s.id==="starting"?"Business registration":s.id==="running"?"Monthly accounting & tax":s.id==="reviewing"?"Reports, filings & audit assistance":"Business closure"}</span></div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.items.map(i=><li key={i}><Check size={17}/>{i}</li>)}</ul><Link className="text-link" href={s.service==="registration"?"/register-business":`/services#${s.service}`}>{s.link}</Link></TabsContent>)}</Tabs><div className="journey-bottom">Start with a free consultation. We’ll explain the next step.</div></div>;}
const chapters=[
 {title:"Understand the requirements.",text:"Tell us what you want to do. We explain the process, documents and work involved in plain language.",label:"A clear starting point",items:["Your business and its structure","The work and records needed","A fee and scope agreed with you"]},
 {title:"Get the details handled.",text:"From registration paperwork to accounts and annual filings, we organize the work and keep you informed.",label:"The work, organized",items:["Documents prepared","Accounts and balances reviewed","Relevant filings coordinated"]},
 {title:"Know your next move.",text:"Understand your position and the actions worth taking—whether that means improving margins, managing cash or completing a closure.",label:"Practical next steps",items:["What needs attention","What the numbers mean","What you can do next"]},
];
export function ClarityStory(){
 const ref=useRef<HTMLElement>(null);const [active,setActive]=useState(0);const [still,setStill]=useState(false);
 useEffect(()=>{const media=matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setStill(media.matches);update();media.addEventListener("change",update);let frame=0;
 const onScroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;const cards=ref.current?.querySelectorAll<HTMLElement>("[data-chapter]");if(!cards)return;let next=0;cards.forEach((card,i)=>{if(card.getBoundingClientRect().top<innerHeight*.55)next=i;});setActive(next);});};onScroll();addEventListener("scroll",onScroll,{passive:true});return()=>{removeEventListener("scroll",onScroll);media.removeEventListener("change",update);cancelAnimationFrame(frame);};},[]);
 return <section className={`clarity-story ${still?"motion-off":""}`} ref={ref}><div className="container story-layout"><div className="story-sticky"><span className="eyebrow">Less uncertainty. More direction.</span><h2>From the details.<br/><span>To a clear plan.</span></h2><div className="story-status" aria-hidden="true"><span className="story-counter">0{active+1}<small> / 03</small></span><div className="story-track"><span style={{transform:`scaleX(${(active+1)/3})`}}/></div><div key={active} className="story-checklist"><strong>{chapters[active].label}</strong>{chapters[active].items.map(i=><div key={i}><Check size={17}/><span>{i}</span></div>)}</div></div></div><div className="story-chapters">{chapters.map((c,i)=><article data-chapter key={c.title} className={active===i?"is-active":""}><span className="chapter-number">0{i+1}</span><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></div></section>;
}
