"use client";
import { useEffect, useRef, useState, type CSSProperties } from "react";
import Link from "next/link";
import { ArrowUpRight, Check, Pause, Play, RotateCcw } from "lucide-react";
const scenes=[
 {id:"starting",label:"Starting",title:"Make your business official.",text:"A suitable structure. The right documents. A clear registration process.",service:"registration",link:"Explore registration",cards:["Business structure","Registration","PAN & tax setup"]},
 {id:"running",label:"Running",title:"Bring order to the everyday.",text:"Accounts, tax work and a useful view of what your business earns and spends.",service:"accounting",link:"Explore monthly support",cards:["Sales & expenses","Monthly accounts","Cash & margins"]},
 {id:"reviewing",label:"Reviewing",title:"Get ready for the next review.",text:"Financial reports, annual filings and support for your appointed independent auditor.",service:"audit",link:"Explore annual support",cards:["Financial reports","Annual filings","Audit assistance"]},
 {id:"closing",label:"Closing",title:"Close with a clear plan.",text:"Review remaining obligations and work through the formal closure steps.",service:"closure",link:"Explore business closure",cards:["Final accounts","Tax obligations","Closure process"]},
];
export function MotionDesk(){
 const [scene,setScene]=useState(0),[paused,setPaused]=useState(false),[replay,setReplay]=useState(0);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{document.documentElement.dataset.motionPaused=String(paused);return()=>{delete document.documentElement.dataset.motionPaused}},[paused]);
 const s=scenes[scene];
 return <div className="motion-desk" ref={ref}><div className="desk-art" key={replay} aria-hidden="true"><div className="desk-orbit orbit-one"/><div className="desk-orbit orbit-two"/><span className="desk-coordinate">HK / YOUR NEXT CHAPTER</span><div className="desk-floor"/><div className="desk-folder"><div className="folder-tab"/><span>HISAB KITAB</span><strong>A little order.<br/>A lot more clarity.</strong><div className="folder-line"/><span>Financial & Tax Consultants</span></div><div className="desk-papers" key={s.id}>{s.cards.map((card,i)=><div className={`desk-paper paper-${i}`} key={card}><span className="paper-number">0{i+1} <ArrowUpRight size={15}/></span><div className="paper-lines"><i/><i/><i/></div><strong>{card}</strong><span className="paper-check"><Check size={14}/> A clear next step</span></div>)}</div><div className="desk-seal"><Check size={25}/><span>Let’s make<br/>it simpler.</span></div><span className="desk-caption">Your business. With the details connected.</span></div><div className="desk-controls"><span>Explore your business stage</span><div><button type="button" onClick={()=>setReplay(v=>v+1)} aria-label="Replay opening animation"><RotateCcw size={15}/></button><button type="button" onClick={()=>setPaused(v=>!v)} aria-label={paused?"Resume motion":"Pause motion"} aria-pressed={paused}>{paused?<Play size={15}/>:<Pause size={15}/>}</button></div></div><div className="desk-tabs" role="tablist" aria-label="Your business stage">{scenes.map((v,i)=><button key={v.id} role="tab" id={`stage-${v.id}`} aria-controls="stage-panel" aria-selected={scene===i} tabIndex={scene===i?0:-1} onClick={()=>setScene(i)} onKeyDown={e=>{if(["ArrowRight","ArrowLeft","Home","End"].includes(e.key)){e.preventDefault();const n=e.key==="Home"?0:e.key==="End"?3:(i+(e.key==="ArrowRight"?1:3))%4;setScene(n);document.getElementById(`stage-${scenes[n].id}`)?.focus()}}}>{v.label}</button>)}</div><div className="desk-panel" role="tabpanel" id="stage-panel" aria-labelledby={`stage-${s.id}`}><h2>{s.title}</h2><p>{s.text}</p><Link href={s.service==="registration"?"/register-business":`/services#${s.service}`} className="text-link">{s.link}<ArrowUpRight size={16}/></Link></div></div>;
}
const chapters=[
 {title:"Every detail has a place.",text:"Sales, expenses, documents and deadlines can pull your attention in different directions. We help you understand the work your business needs.",label:"Understand the work",items:["Registration requirements","Accounts and supporting records","Tax and filing responsibilities"]},
 {title:"Connect the moving parts.",text:"Prepare the documents. Organize the accounts. Coordinate relevant filings and help your appointed auditor with reports and schedules.",label:"Bring the work together",items:["Registration & closure","Monthly accounts & reports","Tax, annual filings & audit assistance"]},
 {title:"Move forward with clarity.",text:"Understand cash, costs and margins. Discuss what needs attention and agree practical next steps for your business.",label:"Know your next step",items:["Understand your position","Discuss the options","Agree the next actions"]},
];
export function FinancialStory(){
 const ref=useRef<HTMLElement>(null),visual=useRef<HTMLDivElement>(null);const [active,setActive]=useState(0);
 useEffect(()=>{let frame=0;const media=matchMedia("(prefers-reduced-motion: reduce)");const update=()=>{frame=0;if(!ref.current||!visual.current)return;const cards=ref.current.querySelectorAll<HTMLElement>("[data-chapter]");let next=0;cards.forEach((el,i)=>{if(el.getBoundingClientRect().top<innerHeight*.65)next=i});setActive(next);const rect=ref.current.getBoundingClientRect();const p=Math.max(0,Math.min(1,(-rect.top+innerHeight*.25)/(rect.height-innerHeight*.6)));visual.current.style.setProperty("--story-progress",String(media.matches?1:p));};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update)};update();addEventListener("scroll",scroll,{passive:true});addEventListener("resize",scroll);media.addEventListener("change",scroll);return()=>{removeEventListener("scroll",scroll);removeEventListener("resize",scroll);media.removeEventListener("change",scroll);cancelAnimationFrame(frame)}},[]);
 return <section className="financial-story" ref={ref}><div className="container"><div className="financial-story-heading"><span className="eyebrow">A business has enough moving parts.</span><h2>Let’s bring them<br/><span>into focus.</span></h2><p>From the everyday details to the bigger decisions.</p></div><div className="financial-story-layout"><div className={`financial-story-visual scene-${active}`} ref={visual} style={{"--story-progress":0} as CSSProperties}><div className="story-graphic" aria-hidden="true"><div className="story-grid"/><div className="story-ring ring-a"/><div className="story-ring ring-b"/><div className="story-hub"><span>HISAB</span><strong>KITAB</strong><span>Clarity, connected.</span></div>{["Records","Accounts","Tax","Next steps"].map((v,i)=><div key={v} className={`story-node node-${i}`}><span className="node-index">0{i+1}</span><span className="node-marks"><i/><i/><i/></span><strong>{v}</strong><Check className="node-check" size={16}/></div>)}<div className="story-thread thread-one"/><div className="story-thread thread-two"/><div className="story-thread thread-three"/></div><div className="visual-caption"><span className="story-counter">0{active+1}<small> / 03</small></span><strong>{chapters[active].label}</strong><div className="visual-progress"><span style={{transform:`scaleX(${(active+1)/3})`}}/></div></div></div><div className="financial-story-chapters">{chapters.map((c,i)=><article key={c.title} data-chapter className={active===i?"is-active":""}><span className="eyebrow">0{i+1} / {c.label}</span><h3>{c.title}</h3><p>{c.text}</p><ul>{c.items.map(v=><li key={v}><Check size={16}/>{v}</li>)}</ul></article>)}</div></div></div></section>;
}
