"use client";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { whatsapp } from "@/lib/business";
const faqs=[
 ["I want to register a business. Where do I begin?","Tell us what you plan to sell or do, who will own the business and the structure you are considering. We help identify the registration route, documents and initial tax setup. Sole proprietorships, private limited companies, joint ventures and organizations need different arrangements.","I want to register a business. Can you help me understand the structure, documents and charges?"],
 ["Sales look good, but cash is tight. Can we discuss it?","Yes. In the free consultation, we discuss collections, stock, upcoming payments and the information available. We suggest what to examine first. A detailed review or forecast is scoped separately if needed.","My business has sales but cash is tight. I’d like a free consultation about collections and cash flow."],
 ["Can you help with tax clearance and annual company filings?","Yes. We help review the relevant records, prepare filing information and coordinate the tax-clearance process. Annual company filings to the Office of Company Registrar are a separate service from income-tax returns.","I need help with tax clearance or annual company filings. Can you explain what I need and the fee?"],
 ["Do you carry out the audit?","We prepare financial reports, reconcile balances, organize schedules and assist with auditor queries. Your appointed independent auditor carries out the audit and issues the audit opinion.","I need financial reports and audit assistance. Can we discuss the period, documents and scope?"],
 ["My business is no longer operating. Do I need to close it formally?","Stopping sales does not automatically close registrations. We review the business structure, accounts, tax matters and registration status, then explain the appropriate closure steps and quote for the work.","My business is no longer operating. I’d like guidance on formally closing it and settling outstanding work."],
 ["What does the free consultation include?","We discuss your business, the problem you are facing and what should happen next. That may include registration requirements, low margins, cash not increasing, rising expenses or advertising results. We offer initial suggestions and explain any further work before you decide.","I’d like to book a free consultation and discuss what my business needs next."],
];
export function ServiceFAQ(){return <Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a,m],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p><a className="text-link faq-whatsapp" href={whatsapp(`Hello Hisab Kitab, ${m}`)} target="_blank" rel="noopener noreferrer">Ask about this on WhatsApp</a></AccordionContent></AccordionItem>)}</Accordion>;}
