import Link from "next/link";
import { SiteMotion } from "@/components/site-motion";
import type { ReactNode } from "react";
import { Check, Phone, MessageCircle } from "lucide-react";
import { SiteHeader, SiteFooter } from "@/components/site-chrome";
import { plans } from "@/lib/plans";
import { phoneHref, whatsapp } from "@/lib/business";
export function PageFrame({children}:{children:ReactNode}){return <><SiteHeader/><main id="main"><SiteMotion/>{children}</main><SiteFooter/></>;}
export function PageIntro({eyebrow,title,description,children}:{eyebrow:string;title:ReactNode;description:string;children?:ReactNode}){return <section className="page-intro"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p>{children}</div></section>;}
export function ConsultationCTA(){return <section className="consultation-cta" id="contact"><div className="container cta-inner"><div><span className="eyebrow">A good place to start</span><h2>Let’s make sense<br/>of your business.</h2><p>Your first consultation is free. Tell us where things stand;<br className="desktop-only"/> we’ll help you work out the next step.</p></div><div className="cta-actions"><Link className="button light" href="/free-consultation#contact">Book a free consultation</Link><a className="cta-phone" href={phoneHref}><Phone size={17}/>+977 974 785 7130</a><a className="text-link light-link" href={whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={16}/>Start on WhatsApp</a></div></div></section>;}
export function PlanCards({full=false}:{full?:boolean}){return <div className="plan-grid">{plans.map((p,i)=><article className={`plan-card ${i===1?"growth-plan":""}`} key={p.id}><span className="eyebrow">{p.label}</span><h3>{p.name}</h3><div className="plan-price">{p.price?<><span>NPR</span><strong>{p.price.toLocaleString("en-IN")}</strong><span>/ month</span></>:<strong>Let’s discuss</strong>}</div><span className="plan-tax">{p.price?"Including VAT":"A quote for your agreed scope"}</span><p>{p.description}</p><ul>{p.highlights.map(h=><li key={h}><Check size={16}/><span>{h}</span></li>)}</ul><Link className={`button ${i===1?"primary":"outline"}`} href={`/free-consultation?plan=${p.id}`}>{p.price?`Discuss ${i===0?"Essentials":"Growth"}`:"Discuss a custom plan"}</Link>{full&&<details className="plan-details"><summary>View the full scope</summary><ul>{p.includes.map(h=><li key={h}>{h}</li>)}</ul></details>}</article>)}</div>;}
export function Process(){return <div className="process-grid">{[["01","Start with a conversation","Tell us about your business, your records and the support you need."],["02","Agree a clear scope","We explain the requirements, work and service fee before starting."],["03","Get the right solution","Get practical support for your registration, accounts, tax matters or closure—and understand your next steps."]].map(([n,t,p])=><div key={n}><span className="step-number">{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div>;}
