"use client";
import { useRef, useState, type FormEvent } from "react";
import Link from "next/link";
import { Calculator, Building2, UserRound, Check } from "lucide-react";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { estimateTax,parseRupees,taxSources,TAX_YEAR,type TaxInput,type TaxResult } from "@/lib/tax";
const money=(n:number)=>"NPR "+n.toLocaleString("en-IN",{maximumFractionDigits:2});
export function TaxCalculator(){
 const [entity,setEntity]=useState<TaxInput["entity"]|"">("");const [turnover,setTurnover]=useState("");const [profit,setProfit]=useState("");const [location,setLocation]=useState<TaxInput["location"]|"">("");const [activity,setActivity]=useState<TaxInput["activity"]|"">("");const [small,setSmall]=useState(false);const [result,setResult]=useState<TaxResult|null>(null);const [error,setError]=useState("");const resultRef=useRef<HTMLDivElement>(null);
 const t=parseRupees(turnover),p=parseRupees(profit);
 const mayQualify=entity==="sole"&&t!==null&&p!==null&&t>0&&((t<=3000000&&p<=300000)||(t>3000000&&t<=10000000&&p<=1000000));
 function change(fn:()=>void){fn();setResult(null);setError("");}
 function submit(e:FormEvent){e.preventDefault();setResult(null);if(!entity){setError("Choose sole proprietorship or company to begin.");return;}if(p===null||(entity==="sole"&&t===null)){setError("Enter valid annual amounts using numbers, commas and up to two decimal places.");return;}if(entity==="sole"&&p>(t??0)){setError("Taxable business profit cannot exceed annual turnover in this simplified estimate. Please check the figures.");return;}
 if(mayQualify&&small&&(!activity||!location)){setError("Choose your business activity and location for the small-business estimate.");return;}if(small&&mayQualify&&activity==="professional"){setError("Professional and expert services are excluded from these small-business rules. Uncheck the small-business option to use the profit-based estimate.");return;}
 const value=estimateTax({entity,turnover:entity==="sole"?t!:0,profit:p,location:location||"metro",activity:activity||"professional",smallBusiness:small&&mayQualify});
 if(mayQualify&&!small)value.notes.unshift("Your figures are within small-business thresholds. D-01 fixed tax or D-02 turnover tax may apply instead, even if this profit-based estimate is zero. Confirm your eligibility before relying on this result.");setError("");setResult(value);requestAnimationFrame(()=>{resultRef.current?.focus({preventScroll:true});if(innerWidth<800)resultRef.current?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});});}
 return <div className="tax-layout"><form className="tax-form" onSubmit={submit} noValidate><fieldset><legend><span className="form-step">01</span>Choose your business structure <span className="required-note">Required</span></legend><RadioGroup value={entity} onValueChange={v=>change(()=>{setEntity(v as TaxInput["entity"]);setSmall(false);})} className="entity-options" aria-label="Business structure" required>{[["sole","Sole proprietorship","Registered business owned by an individual",UserRound],["company","Company","General company income-tax rate",Building2]].map(([value,title,help,Icon])=>{const EntityIcon=Icon as typeof Building2;return <label key={String(value)} className={`entity-option ${entity===value?"selected":""}`}><div><EntityIcon size={23}/><RadioGroupItem value={String(value)} aria-label={String(title)}/></div><strong>{String(title)}</strong><span>{String(help)}</span></label>;})}</RadioGroup></fieldset>
 <fieldset className="amount-fields"><legend><span className="form-step">02</span>Enter your annual figures</legend>{entity!=="company"&&<label>Annual turnover · NPR <span className="required-note">Required for sole proprietor</span><input name="turnover" inputMode="decimal" value={turnover} onChange={e=>change(()=>setTurnover(e.target.value))} placeholder="Enter annual sales" maxLength={24} aria-describedby="turnover-help"/><span className="field-help" id="turnover-help">Total business sales for the year. Example: 45,00,000.</span></label>}<label>Annual taxable business profit · NPR <span className="required-note">Required</span><input name="profit" inputMode="decimal" value={profit} onChange={e=>change(()=>setProfit(e.target.value))} placeholder="Enter taxable profit" maxLength={24} aria-describedby="profit-help"/><span className="field-help" id="profit-help">Profit after tax adjustments, before income tax. Enter 0 if there is no taxable profit.</span></label></fieldset>
 {mayQualify&&<fieldset className="small-tax-panel"><legend><span className="form-step">03</span>Check the small-business option</legend><p>Your figures may qualify for fixed or turnover-based tax. The amount thresholds alone do not confirm eligibility.</p><div className="consent-row"><Checkbox id="small-business" checked={small} onCheckedChange={v=>change(()=>setSmall(v===true))}/><label htmlFor="small-business">Use small-business tax rules. I have confirmed D-01 / D-02 eligibility.</label></div>{small&&<><p className="eligibility-help">For eligible resident natural persons with Nepal-source business income only. Professional/expert and special commission businesses are excluded. Check the official schedule or ask us if unsure.</p><label id="activity-label">Choose your business activity <span className="required-note">Required</span></label><Select value={activity} onValueChange={v=>change(()=>setActivity(v as TaxInput["activity"]))}><SelectTrigger className="form-select" aria-labelledby="activity-label"><SelectValue placeholder="Select business activity"/></SelectTrigger><SelectContent position="popper"><SelectItem value="goods">Ordinary goods / trading</SelectItem><SelectItem value="services">General services</SelectItem><SelectItem value="professional">Professional / expert services</SelectItem></SelectContent></Select><label id="location-label">Choose your business location <span className="required-note">Required</span></label><Select value={location} onValueChange={v=>change(()=>setLocation(v as TaxInput["location"]))}><SelectTrigger className="form-select" aria-labelledby="location-label"><SelectValue placeholder="Select business location"/></SelectTrigger><SelectContent position="popper"><SelectItem value="metro">Metropolitan / sub-metropolitan</SelectItem><SelectItem value="municipality">Municipality</SelectItem><SelectItem value="rural">Rural municipality / other area</SelectItem></SelectContent></Select></>}</fieldset>}
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary calculate-button" type="submit"><Calculator size={18}/>Calculate estimate</button><p className="privacy-note">Your figures stay on this page. They are not saved or sent to an AI service.</p></form>
 <div className="tax-right"><div className={`tax-result ${result?"has-result":""}`} ref={resultRef} tabIndex={-1} aria-live="polite" aria-atomic="true">{result?<><span className="eyebrow">Estimated annual income tax</span><h2>{money(result.total)}</h2><p>{result.basis} · FY {TAX_YEAR}</p><dl>{result.rows.map(r=><div key={r.label}><dt>{r.label}<small>{r.rate===null?"Fixed amount":`${money(r.amount)} × ${+(r.rate*100).toFixed(2)}%`}</small></dt><dd>{money(r.tax)}</dd></div>)}</dl><div className="result-notes">{result.notes.map(n=><p key={n}>{n}</p>)}</div><Link className="button light" href="/free-consultation?service=tax">Discuss your estimate for free</Link></>:<div className="tax-empty"><Calculator size={34}/><span className="eyebrow">Your estimate appears here</span><h2>A clear result.<br/>Step by step.</h2><p>Select your structure and enter the figures. We’ll show the estimated amount and how it was calculated.</p><div className="empty-checks"><span><Check size={16}/>A breakdown of the calculation</span><span><Check size={16}/>The rules and assumptions used</span><span><Check size={16}/>Links to official IRD schedules</span></div></div>}</div><details className="tax-assumptions" open><summary>What this calculator covers</summary><ul><li>A registered resident sole proprietor with business income only, or a company using the general 25% rate.</li><li>D-01 / D-02 rules only when eligibility is confirmed and the figures qualify.</li><li>Concessions, credits, prior payments, carried-forward losses and special-sector rules are excluded.</li><li>This is not a final tax liability or a filing calculation.</li></ul><p>Official sources: <a href={taxSources.natural} target="_blank" rel="noopener noreferrer">IRD natural persons</a> and <a href={taxSources.entity} target="_blank" rel="noopener noreferrer">IRD entities</a>, FY {TAX_YEAR}. Reviewed 6 October 2026.</p></details></div></div>;
}
