import type { z } from "zod";
import { inquirySchema } from "@/lib/inquiry-validation";
import { businessEmail } from "@/lib/business";
const escapeHtml = (value: string) => value.replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" } as Record<string,string>)[character]);
const serviceNames = { registration: "Business registration", accounting: "Monthly accounting", tax: "Tax & compliance", audit: "Audit support", reporting: "Financial reporting", closure: "Business closure", "not-sure": "Help me choose" };
const planNames = { essentials: "Business Essentials", growth: "Business Growth", custom: "Custom plan", "not-sure": "Help me choose" };
export function inquiryEmail(value: z.infer<typeof inquirySchema>, reference: string, from: string) {
  const rows = [ ["Name", value.name], ["Business", value.business || "Not provided"], ["Email", value.email || "Not provided"], ["Phone", value.phone || "Not provided"], ["Service", serviceNames[value.service]], ["Business stage", value.stage], ...(value.service === "accounting" ? [["Plan", planNames[value.plan]]] : []), ["Reference", reference] ];
  const text = ["HISAB KITAB - FREE CONSULTATION INQUIRY", ...rows.map(([label, content]) => `${label}: ${content}`), "", "Message", value.message || "No additional message.", "", "The visitor agreed to be contacted about this inquiry."].join("\n");
  const html = `<!doctype html><html><body style="margin:0;background:#f7f4ee;font-family:Arial,sans-serif;color:#192335"><table role="presentation" width="100%" cellspacing="0" cellpadding="0"><tr><td style="padding:28px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;margin:auto;background:#ffffff;border:1px solid #dedbd7"><tr><td style="padding:28px;background:#652734;color:#ffffff"><div style="font-size:25px;font-weight:bold">HISAB KITAB</div><div style="font-size:14px;margin-top:8px">New free consultation inquiry</div></td></tr><tr><td style="padding:28px"><h1 style="font-size:22px;margin:0 0 20px">A visitor would like to talk.</h1><table width="100%" cellspacing="0" cellpadding="0">${rows.map(([label, content]) => `<tr><th align="left" valign="top" style="width:32%;padding:12px 0;border-bottom:1px solid #dedbd7;font-size:14px">${escapeHtml(label)}</th><td valign="top" style="padding:12px 0 12px 16px;border-bottom:1px solid #dedbd7;font-size:15px;overflow-wrap:anywhere">${escapeHtml(content)}</td></tr>`).join("")}</table><h2 style="font-size:17px;margin:28px 0 12px">Visitor's message</h2><p style="line-height:1.7;font-size:15px;overflow-wrap:anywhere">${escapeHtml(value.message || "No additional message.").replace(/\r?\n/g, "<br>")}</p><p style="font-size:13px;line-height:1.6;color:#535861;margin-top:28px">The visitor agreed to be contacted about this inquiry.${value.email ? " Reply to this email to respond directly to the visitor." : " Contact the visitor using the phone number above."}</p></td></tr><tr><td style="padding:18px 28px;background:#f7f4ee;font-size:13px">Hisab Kitab &middot; Samakhusi, Kathmandu</td></tr></table></td></tr></table></body></html>`;
  return { from, to: [businessEmail], subject: `Free consultation inquiry - ${reference}`, text, html, ...(value.email ? { reply_to: value.email } : {}) };
}
