export const plans = [
  { id: "essentials", name: "Business Essentials", price: 6000, label: "The monthly foundation", description: "Your accounts organized. Your obligations on track. Your business in focus.", highlights: ["Monthly accounts & profit reports", "VAT, e-TDS & tax-payment support", "Payroll & bank reconciliation", "Monthly business consultation"], includes: ["Monthly bookkeeping and sales, expense, and profit reports", "VAT filing, where applicable", "Payroll preparation and salary-related tax calculations", "e-TDS filing and tax-payment coordination", "Advance-tax calculations, reminders, and payment coordination", "Bank reconciliation and bank-related reports", "Projection reports when needed, within the agreed scope", "Tracking and assistance with applicable business renewals", "Monthly consultation on business performance", "Profit-margin tracking and identification of avoidable expenses", "A checklist of upcoming filings, payments, and renewals"] },
  { id: "growth", name: "Business Growth", price: 15000, label: "For a clearer growth strategy", description: "Understand what drives your profit. Make your next decision with better information.", highlights: ["Everything in Business Essentials", "Sales, expense & profitability analysis", "Cash-flow forecasts & advertising returns", "AI-assisted insights, reviewed by us"], includes: ["Everything in Business Essentials", "AI-assisted analysis reviewed using our expertise", "Detailed sales, direct-cost, expense, and payroll analysis", "Cash-flow analysis and forecasting", "Product or service profitability analysis, where records allow", "Advertising-return analysis, where campaign and sales data are available", "Budgeting and comparison of actual results against targets", "Identification of sales gaps, rising costs, and margin pressures", "Business-spending scenarios to evaluate proposed investments", "A monthly action plan with priorities and progress tracking"] },
  { id: "custom", name: "Custom Partnership", price: null, label: "Built around your business", description: "A tailored scope for your operations, reporting needs, and next chapter.", highlights: ["A scope agreed around your needs", "Complex or multi-location operations", "Special reporting & advisory support", "Registration, catch-up or closure work"], includes: ["Accounting support matched to transaction volume and complexity", "Reporting frequency and formats agreed with you", "Support for multiple business units or locations", "Specialized financial and business advisory requirements", "Registration, historical catch-up, or closure assistance as agreed", "A clear scope and quotation before work begins"] },
] as const;
export type PlanId = typeof plans[number]["id"] | "not-sure";
export const comparison = [
  { group: "Monthly accounts & compliance", rows: [["Bookkeeping and bank reconciliation", "Included", "Included", "Tailored"], ["Sales, expense and profit reports", "Included", "Included", "Tailored"], ["Payroll, VAT and e-TDS support", "Included", "Included", "Tailored"], ["Advance-tax and renewal coordination", "Included", "Included", "Tailored"], ["Monthly business consultation", "Included", "Included", "Tailored"]] },
  { group: "Analysis & decision support", rows: [["Profit-margin tracking", "Included", "Included", "Tailored"], ["Projection reports", "As needed, agreed scope", "Included in analysis", "Tailored"], ["Detailed cost and sales analysis", "—", "Included", "Tailored"], ["Cash-flow forecasting", "—", "Included", "Tailored"], ["Advertising-return analysis", "—", "Where data allows", "Tailored"], ["AI-assisted analysis and action plan", "—", "Included", "Tailored"]] },
] as const;
