const earlierPosts=[
 {slug:"profit-is-not-cash",category:"Business clarity",readTime:"4 min read",title:"Your business made a profit. Where is the cash?",description:"Why a healthy profit report can sit beside a tight bank balance—and what to review first.",intro:"A profitable month can still leave a business short of cash. The answer often sits in the timing between making a sale, collecting the money and paying the bills.",sections:[
 {title:"Start with two different questions",paragraphs:["Profit asks whether the revenue earned in a period is greater than the costs recognized for that period. Cash asks how much money is available and when it moves. Both matter, but they describe different parts of the business.","Suppose a business records NPR 8,20,000 of sales and NPR 6,25,000 of operating expenses. The simplified operating profit is NPR 1,95,000. If NPR 2,00,000 of those sales is still unpaid, the bank balance will not show the same result."]},
 {title:"Look at the money waiting to arrive",paragraphs:["Review unpaid customer invoices by age and expected collection date. A sales total can look strong while older invoices accumulate. Separate invoices that are due soon from those already overdue, and record who will follow up.","The useful question is not only how much is owed. It is how likely the collection is, when it is expected and which payments depend on it."]},
 {title:"Check where cash has been committed",paragraphs:["Stock purchases, equipment payments, loan principal and owner withdrawals can use cash without appearing as an equivalent operating expense in the same month. Supplier payments can also relate to purchases made in an earlier period.","For example, buying NPR 1,50,000 of inventory does not automatically mean that the entire amount is an expense in this month’s profit report. The treatment depends on what was sold and how the accounts are prepared. The payment still changes the cash available today."]},
 {title:"Bring three views to the monthly conversation",paragraphs:["Read the profit report beside a receivables list and a short cash outlook. Together they help explain the result, the collections still outstanding and the payments ahead."],bullets:["What generated the profit this month?","Which customer payments are due or overdue?","What supplier, payroll, tax or loan payments are coming next?","How much cash remains available after those commitments?"]},
 {title:"Make the next decision with both views",paragraphs:["A strong month is a reason to review the position carefully before new spending. Confirm collections, planned payments and any unusual items. Then decide whether the business can safely commit cash.","This example is intentionally simplified and does not cover every accounting adjustment. Your monthly reports should reflect your actual records and business circumstances."]}
 ]},
 {slug:"monthly-accounting-checklist",category:"Organized accounts",readTime:"4 min read",title:"A practical month-end checklist for your business",description:"The records and review points that make monthly accounting more useful and less rushed.",intro:"Month-end becomes easier when the records arrive in a consistent way. A small routine each month can reduce missing documents and make the reports easier to explain.",sections:[
 {title:"Collect the records for the same period",paragraphs:["Bring together sales invoices, purchase bills, receipts, bank statements and relevant payment records. Check that they cover the period being reviewed. Keep a note of missing documents rather than leaving unexplained gaps.","Use a consistent naming and filing approach. The goal is to let you and your accountant trace a transaction back to its supporting record without a lengthy search."]},
 {title:"Reconcile the bank activity",paragraphs:["Compare the bank statement with the transactions recorded in your accounts. Identify transfers, charges, outstanding items and entries that need clarification. Matching a total is not enough if individual transactions remain unexplained.","Cash transactions need their own supporting records and review. Business and personal spending should be distinguishable so the reports reflect the business activity."]},
 {title:"Review customers, suppliers and stock",paragraphs:["Check unpaid customer invoices and supplier balances. Look for duplicate entries, disputed amounts, unusual ageing and payments recorded against the wrong invoice.","If the business holds inventory, review the stock records and the effect of purchases and sales on the month’s costs. Confirm unusual shortages or adjustments with the person responsible for the stock."]},
 {title:"Keep payroll and obligations in the routine",paragraphs:["Gather payroll changes, attendance information where relevant and payment records. Review the filings, withholdings and renewals that apply to your registrations and operations.","Tax obligations and deadlines depend on the business and the applicable rules. Ask your accountant to confirm your own requirements. A generic checklist should not be treated as a complete filing calendar."]},
 {title:"Finish with a short business review",paragraphs:["Read the report and write down what changed: sales, direct costs, overheads, margins and collections. Ask about movements you do not understand. Agree the next actions while the period is still fresh."],bullets:["Which records or balances still need confirmation?","What explains the largest change in profit?","Are collections and upcoming payments manageable?","Who will complete each next action, and when?"]},
 {title:"Build a routine you can repeat",paragraphs:["A useful monthly process is one the business can sustain. Agree how records will be shared, who will answer questions and when the report will be reviewed. Hisab Kitab can help define that routine during your first consultation."]}
 ]},
 {slug:"prepare-for-accounting-consultation",category:"Getting started",readTime:"3 min read",title:"What to prepare for your first accounting consultation",description:"A short business overview is enough to start. Here is how to make the conversation useful.",intro:"You do not need perfectly organized accounts to ask for help. The first conversation is about understanding where your business stands and what support would make the next step easier.",sections:[
 {title:"Describe the business in a few sentences",paragraphs:["Explain what you sell, how long you have operated and the structure of the business. Share whether you are just starting, keeping up with monthly operations, preparing for an audit or planning to close.","Approximate transaction volume, number of staff and the tools you use can help us understand the work. Estimates are fine for the first discussion; we can identify the records needed later."]},
 {title:"Explain the problem you want to solve",paragraphs:["Perhaps the books are behind, the profit is hard to understand, customer collections are slow or an important filing needs attention. State the concern and any deadline that is driving it.","If there are several concerns, choose the one that needs attention first. That helps the conversation produce a useful next step instead of an overly broad list of tasks."]},
 {title:"Know what records are available",paragraphs:["You can tell us whether you have bank statements, sales and purchase invoices, payroll records, previous reports and registration details. You do not need to attach those documents to the website inquiry.","Document-sharing arrangements and access requirements should be agreed during onboarding. Please keep passwords, bank details, tax identifiers and confidential records out of the first form."]},
 {title:"Ask about the working arrangement",paragraphs:["A good consultation should help you understand what is included and what is separate. Ask how the monthly routine works, what you need to provide and what reports you will receive."],bullets:["What work is included in the proposed scope?","Is historical catch-up needed before monthly work starts?","Which service fees and statutory payments are separate?","How will records, questions and reports be shared?"]},
 {title:"Leave with a clear next step",paragraphs:["The first consultation is free. It gives us a chance to understand your requirements and propose a suitable scope before you decide. You can begin by phone, WhatsApp or the inquiry form.","For monthly support, Business Essentials and Business Growth offer two starting points. A custom scope can be discussed when your operations or reporting requirements need a different arrangement."]}
 ]}
] as const;

const newPosts=[
 {slug:"register-a-business-nepal",category:"Starting a business",readTime:"4 min read",title:"How to start registering a business in Nepal",description:"Begin with the structure, ownership and documents—not a random list of forms.",intro:"The first question is what kind of business you want to create. A sole proprietorship, private limited company, joint venture or organization can involve different registration routes. Clarify the structure before preparing the paperwork.",sections:[
 {title:"Describe the business and its owners",paragraphs:["Write down what the business will do, who will own it and where it will operate. Consider whether there is one owner, several shareholders or an organization with a different purpose. This helps identify the appropriate route and the questions that need to be answered.","A sole proprietorship and a company are different structures. Do not assume that company registration is the right starting point for every activity. The responsible authority and any industry approval depend on the structure and business."]},
 {title:"For a company, prepare the core documents",paragraphs:["The Office of Company Registrar’s published checklist includes the application, the applicable memorandum and articles, founder identification, and any approval required for the activity. The exact documents depend on the company type and founders.","Foreign investment and joint ventures can need additional permissions and documents. Confirm the current requirements before submitting. Hisab Kitab helps organize the checklist and coordinate preparation."],bullets:["Proposed business name and activities","Ownership, founders and capital information","Identification and relevant company documents","Any approval required for the activity"]},
 {title:"Think beyond the registration certificate",paragraphs:["Ask which tax registrations, local requirements, sector permissions and accounting arrangements apply to your business. A company certificate is one part of the setup; it does not answer every question about beginning operations.","Set up a simple way to keep business bills, sales records and bank activity from the start. Clear records make later reporting and tax work easier."]},
 {title:"Separate the service fee from official charges",paragraphs:["A registration quote should identify the assistance provided and distinguish the consultancy fee from government charges or other statutory payments. Ownership, structure and the work required can change the scope. Avoid relying on a price that does not explain what it covers."]},
 {title:"Start with a free consultation",paragraphs:["Tell Hisab Kitab what you plan to do and who will own the business. We explain the likely process, identify the documents to check and quote for the assistance before work begins."]}
 ],sources:[{label:"Office of Company Registrar: registration documents",url:"https://ocr.gov.np/pages/registration/"}],reviewed:"6 October 2026"},
 {slug:"closing-a-business-nepal",category:"Business closure",readTime:"3 min read",title:"Closing a business: what to review before you stop",description:"Stopping operations and completing formal closure are different steps. Here is where to begin.",intro:"A business can stop selling while its registrations and outstanding work still need attention. Before planning a closure, review the structure, accounts, tax position and formalities together.",sections:[
 {title:"Confirm what is still registered",paragraphs:["List the registrations and permissions the business holds. Include the business or company registration and relevant tax registrations. The closure route depends on the structure and the authorities involved.","Keep current certificates and official correspondence available. They help explain the status and the steps that may still be needed."]},
 {title:"Bring the financial position together",paragraphs:["Review customer balances, supplier amounts, stock, assets, loans, payroll matters and available bank records. Identify items that need confirmation before final reports or closure documents are prepared.","Do not assume that an inactive period means every balance is settled. The records should explain what remains and how it will be addressed."]},
 {title:"Check the tax and filing work",paragraphs:["Discuss relevant returns, payments, tax-clearance requirements and deregistration with your adviser and the responsible office. For companies, also check the company-register requirements. The applicable route and documents need to be confirmed for your circumstances.","The taxpayer portal includes closure services. Simply ceasing transactions should not be treated as confirmation that a tax registration has ended. Ask the responsible tax office to confirm the required process and final status."]},
 {title:"Agree a sequence before starting",paragraphs:["Ask what needs to happen first, which documents are required, who will coordinate each step and what is included in the fee. Processing and final acceptance depend on the responsible authorities; a consultation should not promise a fixed approval date.","Hisab Kitab helps review the position, prepare information and coordinate the relevant formalities. Bring a short overview to a free consultation so we can explain the next step."]}
 ],sources:[{label:"IRD: official taxpayer portal",url:"https://taxpayerportal.ird.gov.np/taxpayer/app.html"},{label:"Office of Company Registrar: current notices and services",url:"https://ocr.gov.np/"}],reviewed:"6 October 2026"},
 {slug:"annual-company-filings-tax-clearance",category:"Tax & annual filings",readTime:"3 min read",title:"Annual company filings and tax clearance: what is the difference?",description:"Know which task you are asking for—and why one document does not replace the others.",intro:"Annual company filings, income-tax returns and tax clearance are related to a business’s records, but they are separate tasks. Knowing the difference makes it easier to request the right service.",sections:[
 {title:"Annual company filing concerns the company register",paragraphs:["Annual company details are submitted to the Office of Company Registrar through the applicable process. The information and supporting documents depend on the company’s circumstances. Confirm the current filing requirements for your own company.","This work is often called barsik bibaran or adhyawati. Hisab Kitab helps prepare the information and coordinate the annual filing. The service fee is NPR 10,000; VAT treatment and any additional work are itemized in your quote."]},
 {title:"An income-tax return reports the tax position",paragraphs:["An income-tax return is a separate filing with the tax authority. It uses the relevant financial information and tax adjustments for the period. Which return applies depends on the taxpayer and the applicable rules.","A financial report or an OCR filing should not be assumed to mean that the income-tax return is complete. Ask which tasks are covered in the engagement and what confirmations will be provided."]},
 {title:"Tax clearance is a separate request",paragraphs:["Tax clearance concerns the taxpayer’s status for the relevant period and applicable requirements. Before requesting it, review the relevant filings, payments and any matters the responsible office needs to address.","Hisab Kitab offers tax-clearance coordination for an additional NPR 5,000. Confirm the period, scope, VAT treatment and any statutory payments in the quote."]},
 {title:"Prepare the reports and coordinate the audit",paragraphs:["We prepare financial statements, supporting schedules and information for your appointed independent auditor. The auditor conducts the audit and issues the opinion. Company report preparation and audit coordination starts at NPR 5,000 plus VAT.","Bring your business structure, financial year and the service you need to a free consultation. We will explain which tasks are included, which are separate and what information is needed."]}
 ],sources:[{label:"Office of Company Registrar: online services and annual reporting",url:"https://ocr.gov.np/"},{label:"Inland Revenue Department: taxpayer services",url:"https://ird.gov.np/"}],reviewed:"6 October 2026"},
] as const;
export const posts=[...newPosts,...earlierPosts] as const;
