export const services = [
 {id:"registration",number:"01",title:"Business registration",summary:"Start with the right structure, documents and registration process.",includes:["Guidance for sole proprietorships, private limited companies, joint ventures and organizations","Document preparation and application coordination","PAN and applicable tax-registration guidance","A clear checklist for your next steps"],fee:"Quoted for your structure and requirements",start:"Tell us what the business will do and who will own it."},
 {id:"accounting",number:"02",title:"Monthly accounting",summary:"Keep accounts and tax work in order. Understand your sales, costs and profit.",includes:["Bookkeeping, bank reconciliation and monthly reports","VAT, e-TDS, payroll and tax-payment support where applicable","Advance tax, renewals and bank reports within the agreed scope","Monthly consultation; deeper analysis with Business Growth"],fee:"NPR 6,000 or NPR 15,000 / month · VAT included",start:"Tell us your transaction volume and the support you need."},
 {id:"tax",number:"03",title:"Tax & annual filings",summary:"Get help with tax returns, clearance and annual company filings (adhyawati).",includes:["Preparation and filing assistance for applicable tax returns","Tax-clearance coordination","Annual company details and OCR filing support","Review of relevant records and outstanding requirements"],fee:"Tax clearance: NPR 5,000 additional · Annual company filing: NPR 10,000",start:"Tell us which filing or certificate you need and the period it covers."},
 {id:"audit",number:"04",title:"Audit assistance",summary:"Prepare financial reports and supporting records for your independent auditor.",includes:["Financial statement and supporting-schedule preparation","Account reconciliation and document organization","Coordination with your appointed auditor","Assistance with information requests and relevant return preparation"],fee:"Company report preparation & audit coordination from NPR 5,000 + VAT",start:"Tell us the financial year, your business structure and your appointed auditor."},
 {id:"reporting",number:"05",title:"Financial reporting",summary:"Understand your business position, margins and cash before the next decision.",includes:["Profit and loss, balance sheet and cash-flow reporting","Bank-related reports and financial projections","Sales, cost and margin analysis within the agreed scope","Reports explained with practical next steps"],fee:"Quoted for the report, purpose and scope",start:"Tell us what the report is for and which period it covers."},
 {id:"closure",number:"06",title:"Business closure",summary:"Work through outstanding accounts, tax matters and formal closure steps.",includes:["Review of accounts, registrations and outstanding obligations","Closure-document preparation assistance","Coordination of relevant tax and registration formalities","A clear sequence of steps for your business structure"],fee:"Quoted after reviewing your business status",start:"Tell us whether the business still operates and which registrations it holds."},
] as const;
export type ServiceId=typeof services[number]["id"];
