import { Suspense } from "react";
import { MapPin, Phone, MessageCircle, Check, Mail } from "lucide-react";
import { PageFrame } from "@/components/site-sections";
import { ServiceFAQ } from "@/components/service-faq";
import { InquiryForm } from "@/components/inquiry-form";
import { businessPhone,phoneHref,whatsapp,businessEmail,emailHref } from "@/lib/business";
import { pageMetadata } from "@/lib/seo";
export const metadata=pageMetadata("Book a Free Consultation","Discuss registration, accounts, cash flow, margins, tax matters or closure. Start your free Hisab Kitab consultation on WhatsApp, by phone or with an inquiry.","/free-consultation");
const topics=[["Starting a business","I’d like a free consultation about registering my business and understanding the requirements."],["Cash or profit concerns","I’d like a free consultation about my business cash flow, expenses and profit margins."],["Tax & annual filings","I’d like a free consultation about tax clearance, annual company filings or my tax obligations."],["Closing a business","I’d like a free consultation about the steps and requirements for closing my business."]];
export default function Consultation(){return <PageFrame><section className="consultation-first" id="contact"><div className="container consultation-layout"><div className="consultation-main"><span className="eyebrow">Your first consultation is free</span><h1>Let’s work out<br/><span>your next step.</span></h1><p>Starting a business? Cash not increasing? Margins too low? Tell us what’s happening. We’ll discuss your situation and suggest what to look at next.</p><div className="contact-actions"><a className="button primary" href={whatsapp()} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>Book free consultation on WhatsApp</a><a className="text-link" href={phoneHref}><Phone size={17}/>{businessPhone}</a></div><div className="consultation-includes"><h2>What we’ll discuss</h2>{["Your business, concerns and available information","Requirements, processes or areas to improve","Initial suggestions and a clear next step"].map(i=><p key={i}><Check size={18}/>{i}</p>)}<span>No service commitment required. Detailed analysis or project work is quoted separately.</span></div><a className="contact-email" href={emailHref}><Mail size={18}/>{businessEmail}</a><div className="contact-detail"><MapPin size={19}/><div><span>Hisab Kitab</span><strong>Samakhusi, Kathmandu</strong></div></div></div><Suspense fallback={<div className="form-panel"><h2>Leave your details</h2><p>You can also begin by phone or WhatsApp.</p></div>}><InquiryForm/></Suspense></div></section><section className="section topic-section"><div className="container"><div className="section-heading"><div><span className="eyebrow">Prefer to start with a question?</span><h2>Choose what you<br/><span>want to discuss.</span></h2></div><p>Each option opens a prepared WhatsApp message. Review it and send when you’re ready.</p></div><div className="topic-grid">{topics.map(([t,m])=><a key={t} href={whatsapp(`Hello Hisab Kitab, ${m}`)} target="_blank" rel="noopener noreferrer"><MessageCircle size={23}/><h3>{t}</h3><span className="read-label">Start a conversation</span></a>)}</div></div></section><section className="section faq-section"><div className="container split-content"><div><span className="eyebrow">A useful first conversation</span><h2>What would<br/><span>you like to know?</span></h2></div><ServiceFAQ/></div></section></PageFrame>;}
