import Link from "next/link";
import { notFound } from "next/navigation";
import { PageFrame,PageIntro } from "@/components/site-sections";
import { posts } from "@/lib/posts";
import { pageMetadata,siteUrl } from "@/lib/seo";
export function generateStaticParams(){return posts.map(p=>({slug:p.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=posts.find(p=>p.slug===slug);return post?pageMetadata(post.title,post.description,`/blog/${slug}`):{};}
export default async function Article({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const post=posts.find(p=>p.slug===slug);if(!post)notFound();const structured={ "@context":"https://schema.org","@type":"Article",headline:post.title,description:post.description,author:{"@type":"Organization",name:"Hisab Kitab"},publisher:{"@type":"Organization",name:"Hisab Kitab"},mainEntityOfPage:siteUrl+"/blog/"+post.slug};
return <PageFrame><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structured).replace(/</g,"\\u003c")}}/><PageIntro eyebrow={`${post.category} · ${post.readTime}`} title={post.title} description="By Hisab Kitab · Financial & Tax Consultants"/><section className="section"><div className="container article-layout"><article className="article-body"><p className="article-intro">{post.intro}</p>{post.sections.map(section=><section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{"bullets" in section&&<ul>{section.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}{"sources" in post&&<div className="article-sources"><h3>Official references</h3><p>Requirements can change. Reviewed {post.reviewed}.</p>{post.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.label}</a>)}</div>}<p className="article-source">General educational guidance. Figures in examples are fictional; accounting treatment and obligations depend on your circumstances.</p><Link className="text-link" href="/blog">Back to the business notebook</Link></article><aside className="article-aside"><h3>Bring your questions.</h3><p>Your first consultation is free. Let’s discuss the records, reports or business decisions you need help with.</p><Link className="button primary" href="/free-consultation">Free consultation</Link></aside></div></section></PageFrame>;}
